version: '3.6'
services:
  redis:
    image: redis/redis-stack:latest
    ports:
    - 8001:8001
  apiserver:
    build:
      context: .
    ports:
    - 43594:43594
    environment:
      WTAPI_CORS_POLICY: http://localhost:3000
      REDIS_HOST: redis
