name: Test & Push

on:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/**'
    - '.vscode/**'
    - '.gitignore'
    - '.gitpod.yml'
    - '**.md'
    - 'LICENSE'
  release:
    types:
    - published
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8

    - name: Restore dependencies
      run: dotnet restore

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
            ${{ runner.os }}-nuget-

    - name: Run tests
      run: dotnet test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: soup-bowl
        password: ${{ secrets.CR_PAT }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build for Edge
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: >
          soupbowl/whatsthis-api:edge,
          ghcr.io/soup-bowl/api:edge
        platforms: >
          linux/amd64
#          linux/arm64 - there's an issue - see:
# https://github.com/soup-bowl/api.whatsth.is/actions/runs/7850693148/job/21426534238#step:7:360
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build for Production
      if: ${{ github.event_name == 'release' }}
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: >
          soupbowl/whatsthis-api:${{ github.event.release.tag_name }},
          ghcr.io/soup-bowl/api:${{ github.event.release.tag_name }},
          soupbowl/whatsthis-api:latest,
          ghcr.io/soup-bowl/api:latest
        platforms: linux/amd64
